### ISSUE TITLE
UI なしスクリーンショットは SkillCommandShortCut の UI が残った状態で撮影してしまう

### ISSUE THREAD

**Issue by pokemonleo** [neguse11/cm3d2_plugins_okiba#24]
夜伽のショートカットは大丈夫ですが、ADVパート選択肢のはこんな感じに
![img20150928221727](https://cloud.githubusercontent.com/assets/7158006/10138129/7c44cb92-662f-11e5-8255-0e11544c61e0.png)

あと関係あるかどうかわかりませんが、身長・足の長さともに 80 （元の制限）を超えたの場合、夜伽の前の会話シーンでメイドの首が異常に伸びたりします

| 乾杯直前 | 乾杯の画面 |
| --- | --- |
| ![img20150928222743](https://cloud.githubusercontent.com/assets/7158006/10138261/423230b0-6630-11e5-9763-63f0ac1f4a0f.png) | ![img20150928222748](https://cloud.githubusercontent.com/assets/7158006/10138262/42368570-6630-11e5-8cb0-f19c68e511a4.png) |

**Comment by neguse11** [comment]
レポートありがとう！
Thanks for your report !

> 夜伽のショートカットは大丈夫ですが、ADVパート選択肢のはこんな感じに

現状は特にスクリーンショット対策はしていないので、調べてみます。
I'll look into it.  Currently, there is no code for screen shot in the shortcut plugin.

> あと関係あるかどうかわかりませんが、身長・足の長さともに 80 （元の制限）を超えたの場合、夜伽の前の会話シーンでメイドの首が異常に伸びたりします

この現象はいつも出ますか？　それとも、時々起こりますか？
Did you always see this glitch ?  Or, is it happens occasionally ?

ショートカットとの直接の関連は無さそうですが、Issue #17 と類似しているように見えます。
It is unlikely connected to the shortcut issue, but it seems related to Issue #17.

**Comment by neguse11** [comment]
再現メモ

昼メニュー → Next → メッセージ欄に「仕事中のメイドとコミュニケーションを行いますか？」と出た状態で選択画面になる

ここで「スクリーンショット」を実行すると、選択肢やメッセージ欄は消えているが、ショートカットキーのラベルだけが残ったスクリーンショットになる

**Comment by pokemonleo** [comment]
時間ができたのでもう少し検証してみたところ
足の長さ 20 ・身長 20 の場合でも乾杯するとき首が少し伸びました・・・（目立ちませんが）

今まで意味がわからなかった PROPSET_OFF をオンにすると伸びなくなった！不思議です！
（PropSetってなんだ？と思いググってきてもピンと来なかったんです・・・）

本文ばかり気にしてタイトルがめちゃくちゃだったのが気が付きませんでした、お恥ずかしい。直してきます。

**Comment by neguse11** [comment]
修正したものを[developブランチにコミット](https://github.com/neguse11/cm3d2_plugins_okiba/commit/16b231f1f68eb9ed5ed850767e31ff80fcadc161)しました。試してみてください。

> 今まで意味がわからなかった PROPSET_OFF をオンにすると伸びなくなった！不思議です！
> （PropSetってなんだ？と思いググってきてもピンと来なかったんです・・・）
- `PROPSET_OFF`は`@PropSet`コマンドによる補正を抑制するためのスイッチです
  - ONにすると、`@PropSet`コマンドを無視するようになります
  - 副作用としてキャラクターの位置やモーションがズレる場合があります
- `@PropSet`は.ksスクリプトファイル内で使用されるパラメーター補正コマンドで、首や肩などの長さを調整するために使われています

.ksスクリプトファイルや`@PropSet`の詳細は本件から外れる話題なので、hf、したらば、4chan 等で聞いてください

**Comment by pokemonleo** [comment]
develop ブランチのものを試しました
スクリーンショットは綺麗に取れました
ありがとうございます！

PROPSET_OFF のままゲーム進んだりすると仕事とか夜伽での手や口がズレまくりますね
今までそれぞれ合わせるために PropSet 使われてたんですね・・・
首が化け物みたいに伸びなくなりますがオフに戻そうか悩ましいところです

詳しい説明本当にありがとうございます！
